apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-management-alpine
        ports:
        - containerPort: 5672  # Puerto de RabbitMQ
        - containerPort: 15672 # Puerto de RabbitMQ Management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        resources:
          requests:
            memory: "400Mi"
            cpu: "500m"
          limits:
            memory: "400Mi"
            cpu: "500m"